import Head from "next/head";
import { SearchBar } from "@/components/SearchBar";
import { Toasts } from "@/containers/Toasts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toasts />
      <section>
        <SearchBar />
      </section>
      <main className="container mx-auto">
        <h1 className="text-7xl">Hello NextJS</h1>
        CITY:
      </main>
    </>
  );
}

// export async function getStaticProps() {
//   const forecast = await forecastService.getForecastForCity("Sofia");

//   return {
//     props: forecast,
//     revalidate: 10800, // 3 hours
//   };
// }
