import { ForecastData } from "@/services/weather/types";
import * as forecastService from "@/services/weather/forecast";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home({ forecast }: ForecastData) {
  console.log(forecast);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-7xl">Hello NextJS</h1>
        CITY:
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const forecast = await forecastService.getForecastForCity("Sofia");

  return {
    props: forecast,
    revalidate: 10800, // 3 hours
  };
}
